---
version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_LOGGERS: "org.apache.zookeeper=WARN"
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: WARN

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.1.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "39092:39092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,state.change.logger=INFO,kafka.coordinator.group=WARN,kafka.cluster=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,kafka.network=WARN,kafka.zk=WARN,kafka.coordinator=WARN,kafka.common=WARN,kafka.utils=WARN,org.apache.zookeeper=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR

  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.1.0
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.0
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.1.0
    hostname: control-center
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
#      - connect
#      - ksql-server
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
#      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
#      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONT#ROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  user-activity-emulator:
    image: ${REGISTRY_URI}/ucu-class/user-activity-emulator:${STUDENT_NAME}-0.1
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      ZK_CONNECT: zookeeper:2181
      MAIN_TOPIC: user-activity-data

  streaming-app:
    image: ${REGISTRY_URI}/ucu-class/streaming-app:${STUDENT_NAME}-0.1
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      SCHEMA_REGISTRY: "http://schema-registry:8081"
      MAIN_TOPIC: user-activity-data
      ENRICHMENT_TOPIC: black-data
      ENRICHED_TOPIC: enriched-user-data

  black-data-provider:
    image: ${REGISTRY_URI}/ucu-class/black-data-provider:${STUDENT_NAME}-0.1
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      ZK_CONNECT: zookeeper:2181
      ENRICHMENT_TOPIC: black-data
      SCHEMA_REGISTRY: "http://schema-registry:8081"
      BLACKIPURL: "https://raw.githubusercontent.com/ihorhrysha/fraud-detection/master/black-data-provider/src/main/resources/black_ip.csv"
      BLACKEMAILURL: "https://raw.githubusercontent.com/ihorhrysha/fraud-detection/master/black-data-provider/src/main/resources/black_email.csv"
      BLACKIPURL_PUBLIC: "https://myip.ms/files/blacklist/csf/latest_blacklist.txt"

  front:
    image: ${REGISTRY_URI}/ucu-class/front:${STUDENT_NAME}-0.1
    depends_on:
      - schema-registry
    ports:
      - "80:80"
