version: '2'
services:
  user-activity-emulator:
    image: $REGISTRY_URI/ucu-class/user-activity-emulator:$STUDENT_NAME-0.1
    environment:
      - KAFKA_BROKERS=$KAFKA_BROKERS # workaround ecs env limitation
      #- KAFKA_BROKERS=kafka:9092
      - ZK_CONNECT=zookeeper:2181
      - MAIN_TOPIC=$MAIN_TOPIC
      - SCHEMA_REGISTRY = $SCHEMA_REGISTRY
      - BLACKIPURL = $BLACKIPURL
      - BLACKEMAILURL = $BLACKEMAILURL

    logging:
      driver: awslogs
      options:
        awslogs-group: streaming-ucu
        awslogs-region: us-east-1
        awslogs-stream-prefix: $STUDENT_NAME
